#!/bin/sh

EMPLOYEES=$HOME/etc/cmp/staff
OUTPUT_DIR="$HOME/Box Documents"
TEMPLATE=$HOME/etc/cmp/template.md

year=`date +%Y`

while read employee
do
    oldIFS="$IFS"
    IFS=:
    set -- $employee
    username=$1
    full_name=$2
    title=$3
    IFS=$oldIFS

    projects=`ssh wiki cmp-extract $username | tidy \
      | pandoc -f html -t markdown --atx-headers`

    dir=$OUTPUT_DIR/$username
    mkdir -p "$dir"

    m4 -DFULL_NAME="$full_name" -DTITLE="$title" \
       -DDATE="`date '+%B %d'`, $year" -DPROJECTS="$projects" $TEMPLATE \
       > $dir/$username-$year.md
done < $EMPLOYEES
